### PR TITLE
Update the local copy of boost C++ library to 1.81.0

### LINKED ISSUE #14: Build failure on Linux ARM64
Hello,

We are working on adding [support](https://stat.ethz.ch/pipermail/bioc-devel/2023-January/019398.html) for R/Bioconductor packages for Linux ARM64 and we face an [issue](https://yikun.github.io/bioconductor-0301/report/NetPathMiner/kunpeng1-install.html) with the build of the NetPathMiner package:
```
##############################################################################
##############################################################################
###
### Running command:
###
###   /home/biocbuild/bbs-3.17-bioc/R/bin/R CMD INSTALL NetPathMiner
###
##############################################################################
##############################################################################


* installing to library ‘/home/biocbuild/bbs-3.17-bioc/R/library’
* installing *source* package ‘NetPathMiner’ ...
** using staged installation
'config' variable 'CPP' is defunct
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for xmlParseFile in -lxml2... yes
checking for readSBML in -lsbml... yes
untarring boost include tree...
libSBML found, finding configuration...
pkg-config tool found
libsbml.pc found. Using pkg-config to extract it.
checking for xml2-config... /usr/bin/xml2-config
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C compiler: ‘gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
using C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
g++ -std=gnu++14  -I"/home/biocbuild/bbs-3.17-bioc/R/include" -DNDEBUG -I. -I/usr/local/include -DHAVE_XML -I/usr/include/libxml2 -DHAVE_SBML -I/usr/include/libxml2  -I/usr/local/include    -fPIC  -g -O2  -Wall  -c PathRanker.cpp -o PathRanker.o
In file included from ./boost/mpl/aux_/na_assert.hpp:23,
                 from ./boost/mpl/arg.hpp:25,
                 from ./boost/mpl/placeholders.hpp:24,
                 from ./boost/iterator/iterator_categories.hpp:17,
                 from ./boost/graph/graph_traits.hpp:25,
                 from ./boost/graph/graph_utility.hpp:29,
                 from PathRanker.cpp:27:
./boost/mpl/assert.hpp:187:21: warning: unnecessary parentheses in declaration of ‘assert_arg’ [-Wparentheses]
  187 | failed ************ (Pred::************
      |                     ^~~~~~~~~~~~~~~~~~~
  188 |       assert_arg( void (*)(Pred), typename assert_arg_pred<Pred>::type )
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  189 |     );
      |     ~                
./boost/mpl/assert.hpp:187:21: note: remove parentheses
  187 | failed ************ (Pred::************
      |                     ^~~~~~~~~~~~~~~~~~~
      |                     -
  188 |       assert_arg( void (*)(Pred), typename assert_arg_pred<Pred>::type )
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  189 |     );
      |     ~                
      |     -
./boost/mpl/assert.hpp:192:21: warning: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Wparentheses]
  192 | failed ************ (boost::mpl::not_<Pred>::************
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  193 |       assert_not_arg( void (*)(Pred), typename assert_arg_pred_not<Pred>::type )
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  194 |     );
      |     ~                
./boost/mpl/assert.hpp:192:21: note: remove parentheses
  192 | failed ************ (boost::mpl::not_<Pred>::************
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     -
  193 |       assert_not_arg( void (*)(Pred), typename assert_arg_pred_not<Pred>::type )
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  194 |     );
      |     ~                
      |     -
In file included from ./boost/smart_ptr/detail/shared_count.hpp:30,
                 from ./boost/smart_ptr/shared_ptr.hpp:32,
                 from ./boost/shared_ptr.hpp:17,
                 from ./boost/property_map/vector_property_map.hpp:14,
                 from ./boost/property_map/property_map.hpp:844,
                 from ./boost/graph/properties.hpp:19,
                 from ./boost/graph/graph_utility.hpp:30,
                 from PathRanker.cpp:27:
./boost/smart_ptr/detail/sp_counted_impl.hpp:81:41: error: ‘boost::detail::sp_typeinfo’ has not been declared
   81 |     virtual void * get_deleter( detail::sp_typeinfo const & )
      |                                         ^~~~~~~~~~~
./boost/smart_ptr/detail/sp_counted_impl.hpp:156:41: error: ‘boost::detail::sp_typeinfo’ has not been declared
  156 |     virtual void * get_deleter( detail::sp_typeinfo const & ti )
      |                                         ^~~~~~~~~~~
./boost/smart_ptr/detail/sp_counted_impl.hpp: In member function ‘virtual void* boost::detail::sp_counted_impl_pd<P, D>::get_deleter(const int&)’:
./boost/smart_ptr/detail/sp_counted_impl.hpp:158:39: error: expected primary-expression before ‘)’ token
  158 |         return ti == BOOST_SP_TYPEID(D)? &reinterpret_cast<char&>( del ): 0;
      |                                       ^
./boost/smart_ptr/detail/sp_counted_impl.hpp:158:22: error: there are no arguments to ‘BOOST_SP_TYPEID’ that depend on a template parameter, so a declaration of ‘BOOST_SP_TYPEID’ must be available [-fpermissive]
  158 |         return ti == BOOST_SP_TYPEID(D)? &reinterpret_cast<char&>( del ): 0;
      |                      ^~~~~~~~~~~~~~~
./boost/smart_ptr/detail/sp_counted_impl.hpp:158:22: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
./boost/smart_ptr/detail/sp_counted_impl.hpp: At global scope:
./boost/smart_ptr/detail/sp_counted_impl.hpp:235:41: error: ‘boost::detail::sp_typeinfo’ has not been declared
  235 |     virtual void * get_deleter( detail::sp_typeinfo const & ti )
      |                                         ^~~~~~~~~~~
./boost/smart_ptr/detail/sp_counted_impl.hpp: In member function ‘virtual void* boost::detail::sp_counted_impl_pda<P, D, A>::get_deleter(const int&)’:
./boost/smart_ptr/detail/sp_counted_impl.hpp:237:41: error: expected primary-expression before ‘)’ token
  237 |         return ti == BOOST_SP_TYPEID( D )? &reinterpret_cast<char&>( d_ ): 0;
      |                                         ^
./boost/smart_ptr/detail/sp_counted_impl.hpp:237:22: error: there are no arguments to ‘BOOST_SP_TYPEID’ that depend on a template parameter, so a declaration of ‘BOOST_SP_TYPEID’ must be available [-fpermissive]
  237 |         return ti == BOOST_SP_TYPEID( D )? &reinterpret_cast<char&>( d_ ): 0;
      |                      ^~~~~~~~~~~~~~~
In file included from ./boost/smart_ptr/shared_ptr.hpp:32,
                 from ./boost/shared_ptr.hpp:17,
                 from ./boost/property_map/vector_property_map.hpp:14,
                 from ./boost/property_map/property_map.hpp:844,
                 from ./boost/graph/properties.hpp:19,
                 from ./boost/graph/graph_utility.hpp:30,
                 from PathRanker.cpp:27:
./boost/smart_ptr/detail/shared_count.hpp: At global scope:
./boost/smart_ptr/detail/shared_count.hpp:446:25: error: ‘sp_typeinfo’ has not been declared
  446 |     void * get_deleter( sp_typeinfo const & ti ) const
      |                         ^~~~~~~~~~~
./boost/smart_ptr/detail/shared_count.hpp: In member function ‘void* boost::detail::shared_count::get_deleter(const int&) const’:
./boost/smart_ptr/detail/shared_count.hpp:448:39: error: cannot convert ‘const int’ to ‘const sp_typeinfo_&’ {aka ‘const std::type_info&’}
  448 |         return pi_? pi_->get_deleter( ti ): 0;
      |                                       ^~
      |                                       |
      |                                       const int
In file included from ./boost/smart_ptr/detail/sp_counted_base.hpp:60,
                 from ./boost/smart_ptr/detail/shared_count.hpp:29,
                 from ./boost/smart_ptr/shared_ptr.hpp:32,
                 from ./boost/shared_ptr.hpp:17,
                 from ./boost/property_map/vector_property_map.hpp:14,
                 from ./boost/property_map/property_map.hpp:844,
                 from ./boost/graph/properties.hpp:19,
                 from ./boost/graph/graph_utility.hpp:30,
                 from PathRanker.cpp:27:
/usr/include/boost/smart_ptr/detail/sp_counted_base_sync.hpp:119:54: note:   initializing argument 1 of ‘virtual void* boost::detail::sp_counted_base::get_deleter(const sp_typeinfo_&)’
  119 |     virtual void * get_deleter( sp_typeinfo_ const & ti ) = 0;
      |                                 ~~~~~~~~~~~~~~~~~~~~~^~
In file included from ./boost/shared_ptr.hpp:17,
                 from ./boost/property_map/vector_property_map.hpp:14,
                 from ./boost/property_map/property_map.hpp:844,
                 from ./boost/graph/properties.hpp:19,
                 from ./boost/graph/graph_utility.hpp:30,
                 from PathRanker.cpp:27:
./boost/smart_ptr/shared_ptr.hpp: At global scope:
./boost/smart_ptr/shared_ptr.hpp:700:50: error: ‘boost::detail::sp_typeinfo’ has not been declared
  700 |     void * _internal_get_deleter( boost::detail::sp_typeinfo const & ti ) const BOOST_NOEXCEPT
      |                                                  ^~~~~~~~~~~
In file included from ./boost/shared_ptr.hpp:17,
                 from ./boost/property_map/vector_property_map.hpp:14,
                 from ./boost/property_map/property_map.hpp:844,
                 from ./boost/graph/properties.hpp:19,
                 from ./boost/graph/graph_utility.hpp:30,
                 from PathRanker.cpp:27:
./boost/smart_ptr/shared_ptr.hpp: In function ‘D* boost::detail::basic_get_deleter(const boost::shared_ptr<U>&)’:
./boost/smart_ptr/shared_ptr.hpp:892:71: error: expected primary-expression before ‘)’ token
  892 |     return static_cast<D *>( p._internal_get_deleter(BOOST_SP_TYPEID(D)) );
      |                                                                       ^
./boost/smart_ptr/shared_ptr.hpp:892:54: error: there are no arguments to ‘BOOST_SP_TYPEID’ that depend on a template parameter, so a declaration of ‘BOOST_SP_TYPEID’ must be available [-fpermissive]
  892 |     return static_cast<D *>( p._internal_get_deleter(BOOST_SP_TYPEID(D)) );
      |                                                      ^~~~~~~~~~~~~~~
In file included from ./boost/shared_array.hpp:17,
                 from ./boost/graph/detail/d_ary_heap.hpp:20,
                 from ./boost/graph/named_function_params.hpp:24,
                 from ./boost/graph/depth_first_search.hpp:21,
                 from ./boost/graph/graph_utility.hpp:32,
                 from PathRanker.cpp:27:
./boost/smart_ptr/shared_array.hpp: At global scope:
./boost/smart_ptr/shared_array.hpp:223:50: error: ‘boost::detail::sp_typeinfo’ has not been declared
  223 |     void * _internal_get_deleter( boost::detail::sp_typeinfo const & ti ) const
      |                                                  ^~~~~~~~~~~
./boost/smart_ptr/shared_array.hpp: In function ‘D* boost::get_deleter(const boost::shared_array<T>&)’:
./boost/smart_ptr/shared_array.hpp:283:74: error: expected primary-expression before ‘)’ token
  283 |     return static_cast< D * >( p._internal_get_deleter( BOOST_SP_TYPEID(D) ) );
      |                                                                          ^
./boost/smart_ptr/shared_array.hpp:283:57: error: there are no arguments to ‘BOOST_SP_TYPEID’ that depend on a template parameter, so a declaration of ‘BOOST_SP_TYPEID’ must be available [-fpermissive]
  283 |     return static_cast< D * >( p._internal_get_deleter( BOOST_SP_TYPEID(D) ) );
      |                                                         ^~~~~~~~~~~~~~~
make: *** [/home/biocbuild/bbs-3.17-bioc/R/etc/Makeconf:198: PathRanker.o] Error 1
ERROR: compilation failed for package ‘NetPathMiner’
* removing ‘/home/biocbuild/bbs-3.17-bioc/R/library/NetPathMiner’
```

The build is OK on Linux x86_64: https://bioconductor.org/checkResults/3.17/bioc-LATEST/NetPathMiner/

And it has a different but probably related problem on Mac ARM64: https://bioconductor.org/checkResults/3.17/bioc-mac-arm64-LATEST/NetPathMiner/kjohnson2-install.html :
```
...
In file included from ./boost/smart_ptr/detail/shared_count.hpp:29:
./boost/smart_ptr/detail/sp_counted_base.hpp:60:11: fatal error: 'boost/smart_ptr/detail/sp_counted_base_sync.hpp' file not found
# include <boost/smart_ptr/detail/sp_counted_base_sync.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [PathRanker.o] Error 1
ERROR: compilation failed for package ‘NetPathMiner’
```

### PR DESCRIPTION
**Pull request by martin-g**
Fixes #14

The new copy is created by following these steps:
- wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
- tar zxvf boost_1_81_0.tar.gz
- mv boost_1_81_0/boost boost
- tar zcvf boost.tar.gz boost
- mv boost.tar.gz NetPathMiner/src

### CODE REVIEW

**Comment by martin-g** [comment]
I've tested it on Linux x86_64 and ARM64:
```
$ ~/bbs-3.17-bioc/R/bin/R CMD build NetPathMiner
* checking for file ‘NetPathMiner/DESCRIPTION’ ... OK
* preparing ‘NetPathMiner’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘NetPathMiner_1.35.6.tar.gz’
```

```
$ ~/bbs-3.17-bioc/R/bin/R CMD check NetPathMiner_1.35.6.tar.gz 
* using log directory ‘/home/biocbuild/git/NetPathMiner.Rcheck’
* using R Under development (unstable) (2023-01-14 r83615)
* using platform: aarch64-unknown-linux-gnu (64-bit)
* R was compiled by
    gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
* running under: Ubuntu 22.04.1 LTS
* using session charset: UTF-8
* checking for file ‘NetPathMiner/DESCRIPTION’ ... OK
* this is package ‘NetPathMiner’ version ‘1.35.6’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘NetPathMiner’ can be installed ... OK
* used C compiler: ‘gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
* used C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
* checking installed package size ... NOTE
  installed size is  7.8Mb
  sub-directories of 1Mb or more:
    doc    2.3Mb
    libs   4.5Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
package 'methods' is used but not declared
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
alpha: no visible global function definition for ‘col2rgb’
alpha: no visible global function definition for ‘rgb’
assignEdgeWeights : wt.func: no visible global function definition for
  ‘median’
assignEdgeWeights: no visible global function definition for
  ‘complete.cases’
assignEdgeWeights: no visible global function definition for ‘na.omit’
assignEdgeWeights : <anonymous>: no visible global function definition
  for ‘na.omit’
bpGetAnnFromXRef: no visible global function definition for ‘na.omit’
bpGetReferences: no visible global function definition for ‘setNames’
bpMetabolicL2: no visible global function definition for ‘setNames’
bpMetabolicL3: no visible global function definition for ‘setNames’
bpSignalingL3: no visible global function definition for ‘na.omit’
bpSplitComplex: no visible global function definition for ‘na.omit’
colorVertexByAttr: no visible global function definition for ‘palette’
colorVertexByAttr: no visible global function definition for
  ‘colorRampPalette’
drawLegend: no visible global function definition for ‘par’
drawLegend: no visible global function definition for ‘plot.new’
drawLegend: no visible global function definition for ‘strwidth’
drawLegend: no visible global function definition for ‘legend’
fetchAttribute: no visible global function definition for ‘na.omit’
fetchAttribute: no visible global function definition for ‘URLencode’
fetchAttribute: no visible global function definition for ‘setNames’
fetchAttribute : <anonymous>: no visible global function definition for
  ‘read.table’
getGeneSetNetworks: no visible global function definition for
  ‘setClass’
getGeneSetNetworks: no visible global function definition for
  ‘representation’
getPaths : <anonymous>: no visible global function definition for
  ‘head’
getPaths: no visible global function definition for ‘.to’
getPaths: no visible global function definition for ‘.from’
getPaths: no visible global function definition for ‘tail’
graph.sizes: no visible global function definition for ‘par’
makeReactionNetwork: no visible global function definition for
  ‘complete.cases’
pathClassifier: no visible binding for global variable ‘sd’
pathClassifier: no visible global function definition for ‘aggregate’
pathCluster: no visible binding for global variable ‘sd’
pathCluster: no visible global function definition for ‘aggregate’
plotAllNetworks: no visible global function definition for ‘palette’
plotAllNetworks: no visible global function definition for ‘par’
plotAllNetworks: no visible global function definition for
  ‘colorRampPalette’
plotClassifierROC: no visible global function definition for ‘palette’
plotClassifierROC: no visible global function definition for ‘layout’
plotClassifierROC: no visible global function definition for ‘na.omit’
plotClusterMatrix: no visible global function definition for ‘rainbow’
plotClusterMatrix: no visible global function definition for ‘image’
plotClusterMatrix: no visible global function definition for ‘axis’
plotClusterProbs: no visible global function definition for ‘rainbow’
plotClusterProbs: no visible global function definition for ‘matplot’
plotClusters: no visible global function definition for ‘rainbow’
plotClusters: no visible global function definition for ‘strwidth’
plotClusters: no visible global function definition for ‘layout’
plotClusters: no visible global function definition for ‘par’
plotClusters: no visible global function definition for ‘legend’
plotCytoscapeGML : col2hex: no visible global function definition for
  ‘rgb’
plotCytoscapeGML : col2hex: no visible global function definition for
  ‘col2rgb’
plotCytoscapeGML: no visible global function definition for
  ‘packageVersion’
plotNetwork: no visible global function definition for ‘palette’
plotNetwork: no visible global function definition for ‘par’
plotNetwork_internal: no visible global function definition for
  ‘palette’
plotNetwork_internal: no visible global function definition for
  ‘setNames’
plotPathClassifier: no visible global function definition for ‘palette’
plotPathClassifier: no visible global function definition for ‘par’
plotPathClassifier: no visible global function definition for ‘layout’
plotPathClassifier: no visible global function definition for ‘barplot’
plotPathClassifier: no visible global function definition for ‘abline’
plotPathClassifier: no visible global function definition for ‘points’
plotPathClassifier: no visible global function definition for ‘axis’
plotPathClassifier: no visible global function definition for ‘image’
plotPathClassifier: no visible global function definition for
  ‘cm.colors’
plotPathClassifier: no visible global function definition for ‘mtext’
plotPathClassifier: no visible global function definition for ‘lines’
plotPathCluster: no visible global function definition for ‘par’
plotPathCluster: no visible global function definition for ‘layout’
plotPathCluster: no visible global function definition for ‘barplot’
plotPathCluster: no visible global function definition for ‘abline’
plotPathCluster: no visible global function definition for ‘axis’
plotPathCluster: no visible global function definition for ‘image’
plotPathCluster: no visible global function definition for ‘cm.colors’
plotPathCluster: no visible global function definition for ‘mtext’
plotPathROC: no visible global function definition for ‘palette’
plotPathROC: no visible global function definition for ‘lines’
plotPathROC: no visible global function definition for ‘axis’
plotPathROC: no visible global function definition for ‘mtext’
plotPathROC: no visible global function definition for ‘legend’
plotPaths: no visible global function definition for ‘palette’
plotPaths: no visible global function definition for ‘par’
process.color: no visible global function definition for
  ‘colorRampPalette’
process.color: no visible global function definition for ‘setNames’
process.layout: no visible global function definition for ‘par’
processNetwork : <anonymous>: no visible global function definition for
  ‘ecdf’
reindexNetwork: no visible binding for global variable ‘head’
stdAttrNames : <anonymous>: no visible global function definition for
  ‘head’
stdAttrNames : <anonymous>: no visible global function definition for
  ‘setNames’
vertexDeleteReconnect: no visible global function definition for ‘.nei’
Undefined global functions or variables:
  .from .nei .to URLencode abline aggregate axis barplot cm.colors
  col2rgb colorRampPalette complete.cases ecdf head image layout legend
  lines matplot median mtext na.omit packageVersion palette par
  plot.new points rainbow read.table representation rgb sd setClass
  setNames strwidth tail
Consider adding
  importFrom("grDevices", "cm.colors", "col2rgb", "colorRampPalette",
             "palette", "rainbow", "rgb")
  importFrom("graphics", "abline", "axis", "barplot", "image", "layout",
             "legend", "lines", "matplot", "mtext", "par", "plot.new",
             "points", "strwidth")
  importFrom("methods", "representation", "setClass")
  importFrom("stats", "aggregate", "complete.cases", "ecdf", "median",
             "na.omit", "sd", "setNames")
  importFrom("utils", "URLencode", "head", "packageVersion",
             "read.table", "tail")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘NPMVignette.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 3 NOTEs
See
  ‘/home/biocbuild/git/NetPathMiner.Rcheck/00check.log’
for details.
```

**Comment by Yikun** [comment]
```
➜  R CMD build NetPathMiner
* checking for file ‘NetPathMiner/DESCRIPTION’ ... OK
* preparing ‘NetPathMiner’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘NetPathMiner_1.35.6.tar.gz’

➜  R CMD check NetPathMiner_1.35.6.tar.gz --no-manual
* using log directory ‘/Users/yikun/R/NetPathMiner.Rcheck’
* using R version 4.2.1 (2022-06-23)
* using platform: aarch64-apple-darwin21.6.0 (64-bit)
* using session charset: UTF-8
* using option ‘--no-manual’
* checking for file ‘NetPathMiner/DESCRIPTION’ ... OK
* this is package ‘NetPathMiner’ version ‘1.35.6’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘NetPathMiner’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
package 'methods' is used but not declared
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... NOTE
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘NPMVignette.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* DONE

Status: 3 NOTEs
See
  ‘/Users/yikun/R/NetPathMiner.Rcheck/00check.log’
for details.
```

I also checked it in my M1 env, it also works!

**Comment by ahmohamed** [comment]
Hi @martin-g and @Yikun,
Thanks for the PR and handling the ARM64 BBS. NetPathMiner unfortunately a tricky package because of the system deps. A few points to consider here:
- The error you've seen is because of missing header file in the bundled boost lib. I'm aware that NetPathMiner cannot build on ARM64 archs (I have M1 Mac), and have investigated the issue to some extent  before giving up because of the complexity involved in supporting that arch.
- The bundled boost lib is a trimmed copy including only the headers used by C++ code (primarily graph). This is intentional to meet the maximum package size (5MB) set by Bioconductor.
- I was reluctant to upgrade boost (or indeed use the ones on the build system, presumably the latest) since some of the code was written by co-authors and they cannot be sure if the package will remain functional after the upgrade.


As you can see, the CI is failing BiocCheck (which you should probably run for any package you're handling) because of the size limit, as expected. From here, there are a few solutions with different levels of effort required:
1. Not support ARM64 (Lazy option).
2. Keep the current old boost for all systems and use BBS boost lib for ARM64. This way all other systems will remain unchanged and ARM64 will compile without changing package size.
3. Re-trim the old boost lib to include the missing headers required to arm64. This can be a can of worms given how old the boost lib is.
4. Ditch the bundled boost all together and use BBS boost libs for all. This is the ideal solution but will require me writing tests to ensure the package remains functional and reproducible.

My personal preference is to go with `2` and put `4` as a future goal. I'm keen to hear from you what you think though.

**Comment by martin-g** [comment]
Thank you for the quick reply here, @ahmohamed !
I understand the problem!
I will close this PR and we will work on option 2!

**Comment by ahmohamed** [comment]
I'm happy help you with that. All I need is a variable to identify the arch that's being build is ARM64. The rest cab be included in `configure.ac` logic. More specifically this line:
https://github.com/ahmohamed/NetPathMiner/blob/master/configure.ac#L29

**Comment by martin-g** [comment]
A new PR is coming!
I'm doing final testing

**Pull request closed without merging**
